### ISSUE TITLE
docs: Installation doesn't work 

### ISSUE THREAD

**Issue by strowi** [aquasecurity/trivy-plugin-kubectl#1]
Hi,

nice idea;) 
Had to manually copy the executable to ~/.krew/bin/kubectl-trivy instead of following the instructions though (`trivy plugin` doesn't exist)
Maybe also publish this via the krew-index?

regards,
strowi

**Comment by knqyf263** [comment]
It is not released yet. Please watch https://github.com/aquasecurity/trivy/pull/878

**Comment by strowi** [comment]
ah sorry, i only took a peek at the latest released versions `--help`. Thx for clearing that up.;)
